version: "3.7"
services:
  java:
    build:
      context: ./java
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build:
      context: ./db
    restart: always
